name: Publish Package

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore Packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish
      run: dotnet publish -c Release
      
    - name: Pack
      run: dotnet pack -c Release ./HtmlRendererCoreNet7.PdfSharp/HtmlRendererCoreNet7.PdfSharp.csproj -o .

    - name: Push
      run: dotnet nuget push "*.nupkg" -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
